version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine


    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
